#!/usr/bin/awk -f
BEGIN {
    FS="\t"
    if (ARGV[1]=="test")
    {test = 1; delete ARGV[1]}
    else
    {test = 0;}
	
}
NR==1 {
    for (i=1; i<NF; i++){
            if($i=="PN"){
                  pncol=i;
              }

              if($i=="Diagnose"){
                    diagcol=i;
                }
        }
}
NR>1 {
    if ( $diagcol~/Con|CON|Kontroll|Normal control/ )
       {
	   if (test==1)
	       print $diagcol "\t=>\t" $pncol 
	   else
	       print $pncol 
       }
       else {
	   if (test==1)
	       print $diagcol "\t=>\tignored"
    }
}
